import * as yup from 'yup';

const validationSchema = yup.object().shape({
  additional_facility: yup.array().of(yup.string()),
  additional_furnishing: yup.array().of(yup.string()),
  additional_room: yup.array().of(yup.string()),
  balconies: yup.string(),
  bedrooms: yup.string(),
  beds: yup.string(),
  booking_price: yup.string(),
  car_parking_open: yup.string(),
  carpet_area: yup.string(),
  carpet_area_size_in: yup.string(),
  description: yup.string(),
  expected_duration_of_stay: yup.string(),
  expected_price: yup.string(),
  expected_price_in_sqft: yup.string(),
  facing_road_width: yup.string(),
  facing_road_width_in: yup.string(),
  floor: yup.string(),
  food_preference: yup.string(),
  furnishing_status: yup.string(),
  gender_preference: yup.string(),
  maximum_tentants_allowed: yup.string(),
  negotiable: yup.boolean(),
  open_side: yup.string(),
  overlooking: yup.array().of(yup.string()),
  ownership_type: yup.string(),
  possession_date: yup.date(),
  preferred_tenants: yup.string(),
  property_for: yup.string(),
  property_status: yup.string(),
  property_type: yup.string(),
  saleable_area: yup.string(),
  saleable_area_size_in: yup.string(),
  special_requirement: yup.string(),
  total_floor: yup.string(),
  tv: yup.string(),
  ac: yup.string(),
  wardrobe: yup.string(),
  work_preference: yup.string(),
  monthly_rent: yup.string(),
  maintance_charge: yup.string(),
  security_deposit: yup.string(),
  available_from: yup.string(),
});

export default validationSchema;
