import * as yup from 'yup';

const validationSchema = yup.object().shape({
  additional_facility: yup.array().of(yup.string()),
  additional_furnishing: yup.array().of(yup.string()),
  additional_room: yup.array().of(yup.string()),
  balconies: yup.string().required('Balconies is required'),
  bedrooms: yup.string().required('Bedrooms is required'),
  beds: yup.string().required('Beds is required'),
  booking_price: yup.string().required('Booking price is required'),
  car_parking_open: yup.string().required('Car parking (open) is required'),
  carpet_area: yup.string().required('Carpet area is required'),
  carpet_area_size_in: yup.string().required('Carpet area size is required'),
  description: yup.string().required('Description is required'),
  expected_duration_of_stay: yup.string().required('Expected duration of stay is required'),
  expected_price: yup.string().required('Expected price is required'),
  expected_price_in_sqft: yup.string().required('Expected price in sqft is required'),
  facing_road_width: yup.string().required('Facing road width is required'),
  facing_road_width_in: yup.string().required('Facing road width unit is required'),
  floor: yup.string().required('Floor is required'),
  food_preference: yup.string().required('Food preference is required'),
  furnishing_status: yup.string().required('Furnishing status is required'),
  gender_preference: yup.string().required('Gender preference is required'),
  maximum_tentants_allowed: yup.string().required('Maximum tenants allowed is required'),
  negotiable: yup.boolean().required('Negotiable is required'),
  open_side: yup.string().required('Open side is required'),
  overlooking: yup.array().of(yup.string()),
  ownership_type: yup.string().required('Ownership type is required'),
  possession_date: yup.date().required('Possession date is required'),
  preferred_tenants: yup.string().required('Preferred tenants is required'),
  property_for: yup.string().required('Property for is required'),
  property_status: yup.string().required('Property status is required'),
  property_type: yup.string().required('Property type is required'),
  saleable_area: yup.string().required('Saleable area is required'),
  saleable_area_size_in: yup.string().required('Saleable area size is required'),
  special_requirement: yup.string().required('Special requirement is required'),
  total_floor: yup.string().required('Total floor is required'),
  tv: yup.string().required('TV availability is required'),
  wardrobe: yup.string().required('Wardrobe availability is required'),
  work_preference: yup.string().required('Work preference is required'),
  monthly_rent: yup.string().required('Monthly rent is required'),
  maintance_charge: yup.string().required('Maintenance charge is required'),
  security_deposit: yup.string().required('Security deposit is required'),
  available_from: yup.string().required('Available from date is required'),
});

export default validationSchema;
